### ISSUE TITLE
Unable to modify "site-title" png image

### ISSUE THREAD

**Issue by noel-emmanuel** [eliottvincent/bay#3]
### "site-title" custom png image resets to "BAY THEME" after re-running jekyll serve.

![img](https://i.ibb.co/BBd4h8N/Screenshot-from-2020-11-17-11-26-13.png "what i want to change")
![img](https://i.ibb.co/L1Pvp7S/New-Project-1.png)

## To recreate this issue: 

1. Create your own header image from the same dimensions as the default one: 160 x 28 pixels.
2. Create 2 copies of this png file with transparent background.
3. Rename them as `title.png` and `title@2x.png` and replace them at  `_site/assets/img/`
4. Re-run Jekyll and it should overwrite the files we just created.

I want to either:
1. display my name as just text
2. a way to use this custom png as the header / logo:
![img](https://i.ibb.co/C1nqj9S/New-Project.png)

**Comment by eliottvincent** [comment]
Hello Noel.

The `_site` directory contains the build of your Jekyll website, you shouldn't touch to it. Its content is refreshed every time you run `jekyll serve`, hence overriding any modifications you would do inside it.
Please have a look here: https://jekyllrb.com/docs/structure/

So to edit the assets, simply check in the `assets` directory ;)

**Comment by noel-emmanuel** [comment]
For future reference,

I got the custom header img to show up by:
1. making an `assets` directory
2. `cd` into `assets`
3. make another directory called `img`
4. `cd` into `img`
5. have 2 png files named: `title.png` and `title@2x.png`
6. When re-running `jekyll-serve` you should see your custom png overwriting the default one. 

Links I used to come to this conclusion
* https://github.com/turing4ever/turing4ever.github.io/tree/master/assets
* https://turing4ever.github.io/2018/10/17/how-to-replace-favicon-and-logo.html
* https://jekyllrb.com/docs/themes/#overriding-theme-defaults
* https://github.com/kitian616/jekyll-TeXt-theme/issues/77

**Comment by rachelstephlee** [comment]
my issue is that somehow when i put my own `title.png` in, my own png's height is much smaller than the default BAY THEME. how am i supposed to generate the .png so that it would be bigger? I tried forcing the image width/height, but any height inputs gets overrode and the width just distorts the image.

**Comment by eliottvincent** [comment]
A 40px high picture should be all right (rendered height is 28px). Width can be anything. What's the size of your current picture? Do you have a screenshot of the issue?

**Comment by rachelstephlee** [comment]
yea i sorted it out. i was using illustrator to make the image, but when it outputs on transparent background and gets uploaded on the page, it doesn't like the dimensions as much. since the title is just a transparent png of text in futura font, it might be useful to have a way to generate it for users (so they dont have to generate their own). i also would have appreciated it if it were added in the documentation that's how you change the title (i would imagine no one would want a website titled "BAY THEME" starting out). 

thanks for the fast response, and, really, beautiful template.

**Comment by eliottvincent** [comment]
Glad it's working now! The Futura font is a paid and licensed font, that's why I don't provide anything to automatically generate the picture. I'll add some instructions in the documentation though, thanks for the feedback.
